name: CI/CD Pipeline - Test, Train, Commit Model

on:
  push:
    branches:
      - main

jobs:
  test-train-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Run training script
      run: python src/housing-predict-ml.py

    - name: Commit and push model artifact
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add model/model.pkl
        git diff --cached --quiet || (git commit -m "Update trained model artifact" && git push)
